// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace Cryptsy.SampleResponse1JsonTypes
{

    internal class Buyorder
    {

        [JsonProperty( "price" )]
        public string Price
        {
            get;
            set;
        }

        [JsonProperty( "quantity" )]
        public string Quantity
        {
            get;
            set;
        }

        [JsonProperty( "total" )]
        public string Total
        {
            get;
            set;
        }

        public float getPriceWhereQuantityNotNull( Buyorder[] orders )
        {
            for( int i = 0; i < orders.Length; i++ )
            {
                if( !orders[i].Quantity.Equals( "0.00000000" ) )
                {
                    float result = 0;
                    float.TryParse( orders[i].Price, out result );
                    return result;
                }
            }
            return 0;
        }
    }

}
