// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cryptsy.SampleResponse1JsonTypes;

namespace Cryptsy.SampleResponse1JsonTypes
{

    internal class Buyorder110
    {

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("quantity")]
        public string Quantity { get; set; }

        [JsonProperty("total")]
        public string Total { get; set; }
    }

}
