// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace Cryptsy.SampleResponse1JsonTypes
{

    internal class Markets
    {

        [JsonProperty( "ADT/XPM" )]
        public ADTXPM ADTXPM
        {
            get;
            set;
        }

        [JsonProperty( "ASC/XPM" )]
        public ASCXPM ASCXPM
        {
            get;
            set;
        }

        [JsonProperty( "CENT/XPM" )]
        public CENTXPM CENTXPM
        {
            get;
            set;
        }

        [JsonProperty( "COL/XPM" )]
        public COLXPM COLXPM
        {
            get;
            set;
        }

        [JsonProperty( "IFC/XPM" )]
        public IFCXPM IFCXPM
        {
            get;
            set;
        }

        [JsonProperty( "NET/XPM" )]
        public NETXPM NETXPM
        {
            get;
            set;
        }

        [JsonProperty( "TIX/XPM" )]
        public TIXXPM TIXXPM
        {
            get;
            set;
        }

        [JsonProperty( "ADT/LTC" )]
        public ADTLTC ADTLTC
        {
            get;
            set;
        }

        [JsonProperty( "ASC/LTC" )]
        public ASCLTC ASCLTC
        {
            get;
            set;
        }

        [JsonProperty( "CENT/LTC" )]
        public CENTLTC CENTLTC
        {
            get;
            set;
        }

        [JsonProperty( "CNC/LTC" )]
        public CNCLTC CNCLTC
        {
            get;
            set;
        }

        [JsonProperty( "COL/LTC" )]
        public COLLTC COLLTC
        {
            get;
            set;
        }

        [JsonProperty( "CPR/LTC" )]
        public CPRLTC CPRLTC
        {
            get;
            set;
        }

        [JsonProperty( "DBL/LTC" )]
        public DBLLTC DBLLTC
        {
            get;
            set;
        }

        [JsonProperty( "DGC/LTC" )]
        public DGCLTC DGCLTC
        {
            get;
            set;
        }

        [JsonProperty( "DVC/LTC" )]
        public DVCLTC DVCLTC
        {
            get;
            set;
        }

        [JsonProperty( "ELP/LTC" )]
        public ELPLTC ELPLTC
        {
            get;
            set;
        }

        [JsonProperty( "EZC/LTC" )]
        public EZCLTC EZCLTC
        {
            get;
            set;
        }

        [JsonProperty( "FLO/LTC" )]
        public FLOLTC FLOLTC
        {
            get;
            set;
        }

        [JsonProperty( "GLD/LTC" )]
        public GLDLTC GLDLTC
        {
            get;
            set;
        }

        [JsonProperty( "GME/LTC" )]
        public GMELTC GMELTC
        {
            get;
            set;
        }

        [JsonProperty( "IFC/LTC" )]
        public IFCLTC IFCLTC
        {
            get;
            set;
        }

        [JsonProperty( "JKC/LTC" )]
        public JKCLTC JKCLTC
        {
            get;
            set;
        }

        [JsonProperty( "MEC/LTC" )]
        public MECLTC MECLTC
        {
            get;
            set;
        }

        [JsonProperty( "MEM/LTC" )]
        public MEMLTC MEMLTC
        {
            get;
            set;
        }

        [JsonProperty( "MST/LTC" )]
        public MSTLTC MSTLTC
        {
            get;
            set;
        }

        [JsonProperty( "NET/LTC" )]
        public NETLTC NETLTC
        {
            get;
            set;
        }

        [JsonProperty( "PXC/LTC" )]
        public PXCLTC PXCLTC
        {
            get;
            set;
        }

        [JsonProperty( "RED/LTC" )]
        public REDLTC REDLTC
        {
            get;
            set;
        }

        [JsonProperty( "RYC/LTC" )]
        public RYCLTC RYCLTC
        {
            get;
            set;
        }

        [JsonProperty( "SXC/LTC" )]
        public SXCLTC SXCLTC
        {
            get;
            set;
        }

        [JsonProperty( "TIX/LTC" )]
        public TIXLTC TIXLTC
        {
            get;
            set;
        }

        [JsonProperty( "WDC/LTC" )]
        public WDCLTC WDCLTC
        {
            get;
            set;
        }

        [JsonProperty( "XPM/LTC" )]
        public XPMLTC XPMLTC
        {
            get;
            set;
        }

        [JsonProperty( "YAC/LTC" )]
        public YACLTC YACLTC
        {
            get;
            set;
        }

        [JsonProperty( "ALF/BTC" )]
        public ALFBTC ALFBTC
        {
            get;
            set;
        }

        [JsonProperty( "AMC/BTC" )]
        public AMCBTC AMCBTC
        {
            get;
            set;
        }

        [JsonProperty( "ANC/BTC" )]
        public ANCBTC ANCBTC
        {
            get;
            set;
        }

        [JsonProperty( "ARG/BTC" )]
        public ARGBTC ARGBTC
        {
            get;
            set;
        }

        [JsonProperty( "BQC/BTC" )]
        public BQCBTC BQCBTC
        {
            get;
            set;
        }

        [JsonProperty( "BTB/BTC" )]
        public BTBBTC BTBBTC
        {
            get;
            set;
        }

        [JsonProperty( "BTE/BTC" )]
        public BTEBTC BTEBTC
        {
            get;
            set;
        }

        [JsonProperty( "BTG/BTC" )]
        public BTGBTC BTGBTC
        {
            get;
            set;
        }

        [JsonProperty( "BUK/BTC" )]
        public BUKBTC BUKBTC
        {
            get;
            set;
        }

        [JsonProperty( "CAP/BTC" )]
        public CAPBTC CAPBTC
        {
            get;
            set;
        }

        [JsonProperty( "CGB/BTC" )]
        public CGBBTC CGBBTC
        {
            get;
            set;
        }

        [JsonProperty( "CLR/BTC" )]
        public CLRBTC CLRBTC
        {
            get;
            set;
        }

        [JsonProperty( "CMC/BTC" )]
        public CMCBTC CMCBTC
        {
            get;
            set;
        }

        [JsonProperty( "CRC/BTC" )]
        public CRCBTC CRCBTC
        {
            get;
            set;
        }

        [JsonProperty( "CSC/BTC" )]
        public CSCBTC CSCBTC
        {
            get;
            set;
        }

        [JsonProperty( "DGC/BTC" )]
        public DGCBTC DGCBTC
        {
            get;
            set;
        }

        [JsonProperty( "ELC/BTC" )]
        public ELCBTC ELCBTC
        {
            get;
            set;
        }

        [JsonProperty( "EMD/BTC" )]
        public EMDBTC EMDBTC
        {
            get;
            set;
        }

        [JsonProperty( "FRC/BTC" )]
        public FRCBTC FRCBTC
        {
            get;
            set;
        }

        [JsonProperty( "FRK/BTC" )]
        public FRKBTC FRKBTC
        {
            get;
            set;
        }

        [JsonProperty( "FST/BTC" )]
        public FSTBTC FSTBTC
        {
            get;
            set;
        }

        [JsonProperty( "FTC/BTC" )]
        public FTCBTC FTCBTC
        {
            get;
            set;
        }

        [JsonProperty( "GDC/BTC" )]
        public GDCBTC GDCBTC
        {
            get;
            set;
        }

        [JsonProperty( "GLC/BTC" )]
        public GLCBTC GLCBTC
        {
            get;
            set;
        }

        [JsonProperty( "GLD/BTC" )]
        public GLDBTC GLDBTC
        {
            get;
            set;
        }

        [JsonProperty( "GLX/BTC" )]
        public GLXBTC GLXBTC
        {
            get;
            set;
        }

        [JsonProperty( "HBN/BTC" )]
        public HBNBTC HBNBTC
        {
            get;
            set;
        }

        [JsonProperty( "IXC/BTC" )]
        public IXCBTC IXCBTC
        {
            get;
            set;
        }

        [JsonProperty( "KGC/BTC" )]
        public KGCBTC KGCBTC
        {
            get;
            set;
        }

        [JsonProperty( "LK7/BTC" )]
        public LK7BTC LK7BTC
        {
            get;
            set;
        }

        [JsonProperty( "LKY/BTC" )]
        public LKYBTC LKYBTC
        {
            get;
            set;
        }

        [JsonProperty( "LTC/BTC" )]
        public LTCBTC LTCBTC
        {
            get;
            set;
        }

        [JsonProperty( "MEC/BTC" )]
        public MECBTC MECBTC
        {
            get;
            set;
        }

        [JsonProperty( "MNC/BTC" )]
        public MNCBTC MNCBTC
        {
            get;
            set;
        }

        [JsonProperty( "NBL/BTC" )]
        public NBLBTC NBLBTC
        {
            get;
            set;
        }

        [JsonProperty( "NEC/BTC" )]
        public NECBTC NECBTC
        {
            get;
            set;
        }

        [JsonProperty( "NMC/BTC" )]
        public NMCBTC NMCBTC
        {
            get;
            set;
        }

        [JsonProperty( "NRB/BTC" )]
        public NRBBTC NRBBTC
        {
            get;
            set;
        }

        [JsonProperty( "NVC/BTC" )]
        public NVCBTC NVCBTC
        {
            get;
            set;
        }

        [JsonProperty( "PHS/BTC" )]
        public PHSBTC PHSBTC
        {
            get;
            set;
        }

        [JsonProperty( "Points/BTC" )]
        public PointsBTC PointsBTC
        {
            get;
            set;
        }

        [JsonProperty( "PPC/BTC" )]
        public PPCBTC PPCBTC
        {
            get;
            set;
        }

        [JsonProperty( "PTS/BTC" )]
        public PTSBTC PTSBTC
        {
            get;
            set;
        }

        [JsonProperty( "PXC/BTC" )]
        public PXCBTC PXCBTC
        {
            get;
            set;
        }

        [JsonProperty( "PYC/BTC" )]
        public PYCBTC PYCBTC
        {
            get;
            set;
        }

        [JsonProperty( "QRK/BTC" )]
        public QRKBTC QRKBTC
        {
            get;
            set;
        }

        [JsonProperty( "SBC/BTC" )]
        public SBCBTC SBCBTC
        {
            get;
            set;
        }

        [JsonProperty( "SPT/BTC" )]
        public SPTBTC SPTBTC
        {
            get;
            set;
        }

        [JsonProperty( "SRC/BTC" )]
        public SRCBTC SRCBTC
        {
            get;
            set;
        }

        [JsonProperty( "TAG/BTC" )]
        public TAGBTC TAGBTC
        {
            get;
            set;
        }

        [JsonProperty( "TEK/BTC" )]
        public TEKBTC TEKBTC
        {
            get;
            set;
        }

        [JsonProperty( "TRC/BTC" )]
        public TRCBTC TRCBTC
        {
            get;
            set;
        }

        [JsonProperty( "WDC/BTC" )]
        public WDCBTC WDCBTC
        {
            get;
            set;
        }

        [JsonProperty( "XJO/BTC" )]
        public XJOBTC XJOBTC
        {
            get;
            set;
        }

        [JsonProperty( "XPM/BTC" )]
        public XPMBTC XPMBTC
        {
            get;
            set;
        }

        [JsonProperty( "YAC/BTC" )]
        public YACBTC YACBTC
        {
            get;
            set;
        }

        [JsonProperty( "ZET/BTC" )]
        public ZETBTC ZETBTC
        {
            get;
            set;
        }

        [JsonProperty( "DOGE/LTC" )]
        public DOGELTC DOGELTC
        {
            get;
            set;
        }

        [JsonProperty( "DOGE/BTC" )]
        public DOGEBTC DOGEBTC
        {
            get;
            set;
        }
    }

}
