// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cryptsy.SampleResponse1JsonTypes;

namespace Cryptsy.SampleResponse1JsonTypes
{

    internal class Return
    {

        [JsonProperty("markets")]
        public Markets Markets { get; set; }
    }

}
