// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cryptsy.BalancesJsonTypes;

namespace Cryptsy.BalancesJsonTypes
{

    internal class BalancesAvailable
    {

        [JsonProperty("ALF")]
        public string ALF { get; set; }

        [JsonProperty("AMC")]
        public string AMC { get; set; }

        [JsonProperty("ADT")]
        public string ADT { get; set; }

        [JsonProperty("ANC")]
        public string ANC { get; set; }

        [JsonProperty("ARG")]
        public string ARG { get; set; }

        [JsonProperty("ASC")]
        public string ASC { get; set; }

        [JsonProperty("BQC")]
        public string BQC { get; set; }

        [JsonProperty("BET")]
        public string BET { get; set; }

        [JsonProperty("BTB")]
        public string BTB { get; set; }

        [JsonProperty("BTC")]
        public string BTC { get; set; }

        [JsonProperty("BTG")]
        public string BTG { get; set; }

        [JsonProperty("CAP")]
        public string CAP { get; set; }

        [JsonProperty("BTE")]
        public string BTE { get; set; }

        [JsonProperty("CSC")]
        public string CSC { get; set; }

        [JsonProperty("CNC")]
        public string CNC { get; set; }

        [JsonProperty("COL")]
        public string COL { get; set; }

        [JsonProperty("CPR")]
        public string CPR { get; set; }

        [JsonProperty("CLR")]
        public string CLR { get; set; }

        [JsonProperty("CMC")]
        public string CMC { get; set; }

        [JsonProperty("CRC")]
        public string CRC { get; set; }

        [JsonProperty("BUK")]
        public string BUK { get; set; }

        [JsonProperty("CGB")]
        public string CGB { get; set; }

        [JsonProperty("Points")]
        public string Points { get; set; }

        [JsonProperty("DVC")]
        public string DVC { get; set; }

        [JsonProperty("DMD")]
        public string DMD { get; set; }

        [JsonProperty("DGC")]
        public string DGC { get; set; }

        [JsonProperty("DOGE")]
        public string DOGE { get; set; }

        [JsonProperty("DBL")]
        public string DBL { get; set; }

        [JsonProperty("ELC")]
        public string ELC { get; set; }

        [JsonProperty("ELP")]
        public string ELP { get; set; }

        [JsonProperty("DEM")]
        public string DEM { get; set; }

        [JsonProperty("EMD")]
        public string EMD { get; set; }

        [JsonProperty("EZC")]
        public string EZC { get; set; }

        [JsonProperty("FST")]
        public string FST { get; set; }

        [JsonProperty("FTC")]
        public string FTC { get; set; }

        [JsonProperty("FLO")]
        public string FLO { get; set; }

        [JsonProperty("FRK")]
        public string FRK { get; set; }

        [JsonProperty("FRC")]
        public string FRC { get; set; }

        [JsonProperty("GLX")]
        public string GLX { get; set; }

        [JsonProperty("GME")]
        public string GME { get; set; }

        [JsonProperty("GLC")]
        public string GLC { get; set; }

        [JsonProperty("GLD")]
        public string GLD { get; set; }

        [JsonProperty("GDC")]
        public string GDC { get; set; }

        [JsonProperty("HBN")]
        public string HBN { get; set; }

        [JsonProperty("HYC")]
        public string HYC { get; set; }

        [JsonProperty("IFC")]
        public string IFC { get; set; }

        [JsonProperty("IXC")]
        public string IXC { get; set; }

        [JsonProperty("XJO")]
        public string XJO { get; set; }

        [JsonProperty("JKC")]
        public string JKC { get; set; }

        [JsonProperty("KGC")]
        public string KGC { get; set; }

        [JsonProperty("LTC")]
        public string LTC { get; set; }

        [JsonProperty("LK7")]
        public string LK7 { get; set; }

        [JsonProperty("LKY")]
        public string LKY { get; set; }

        [JsonProperty("MST")]
        public string MST { get; set; }

        [JsonProperty("MEC")]
        public string MEC { get; set; }

        [JsonProperty("MEM")]
        public string MEM { get; set; }

        [JsonProperty("MNC")]
        public string MNC { get; set; }

        [JsonProperty("NMC")]
        public string NMC { get; set; }

        [JsonProperty("NAN")]
        public string NAN { get; set; }

        [JsonProperty("NEC")]
        public string NEC { get; set; }

        [JsonProperty("NET")]
        public string NET { get; set; }

        [JsonProperty("NBL")]
        public string NBL { get; set; }

        [JsonProperty("NRB")]
        public string NRB { get; set; }

        [JsonProperty("NVC")]
        public string NVC { get; set; }

        [JsonProperty("ORB")]
        public string ORB { get; set; }

        [JsonProperty("PYC")]
        public string PYC { get; set; }

        [JsonProperty("PPC")]
        public string PPC { get; set; }

        [JsonProperty("CENT")]
        public string CENT { get; set; }

        [JsonProperty("PHS")]
        public string PHS { get; set; }

        [JsonProperty("PXC")]
        public string PXC { get; set; }

        [JsonProperty("XPM")]
        public string XPM { get; set; }

        [JsonProperty("PTS")]
        public string PTS { get; set; }

        [JsonProperty("QRK")]
        public string QRK { get; set; }

        [JsonProperty("RED")]
        public string RED { get; set; }

        [JsonProperty("RYC")]
        public string RYC { get; set; }

        [JsonProperty("SRC")]
        public string SRC { get; set; }

        [JsonProperty("SXC")]
        public string SXC { get; set; }

        [JsonProperty("SPT")]
        public string SPT { get; set; }

        [JsonProperty("SBC")]
        public string SBC { get; set; }

        [JsonProperty("STR")]
        public string STR { get; set; }

        [JsonProperty("TAG")]
        public string TAG { get; set; }

        [JsonProperty("TEK")]
        public string TEK { get; set; }

        [JsonProperty("TRC")]
        public string TRC { get; set; }

        [JsonProperty("TIX")]
        public string TIX { get; set; }

        [JsonProperty("TGC")]
        public string TGC { get; set; }

        [JsonProperty("UNO")]
        public string UNO { get; set; }

        [JsonProperty("WDC")]
        public string WDC { get; set; }

        [JsonProperty("XNC")]
        public string XNC { get; set; }

        [JsonProperty("YAC")]
        public string YAC { get; set; }

        [JsonProperty("ZET")]
        public string ZET { get; set; }
    }

}
