// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cryptsy.BalancesJsonTypes;

namespace Cryptsy.BalancesJsonTypes
{

    internal class Return
    {

        [JsonProperty("balances_available")]
        public BalancesAvailable BalancesAvailable { get; set; }

        [JsonProperty("balances_hold")]
        public BalancesHold BalancesHold { get; set; }

        [JsonProperty("servertimestamp")]
        public int Servertimestamp { get; set; }

        [JsonProperty("servertimezone")]
        public string Servertimezone { get; set; }

        [JsonProperty("serverdatetime")]
        public string Serverdatetime { get; set; }

        [JsonProperty("openordercount")]
        public int Openordercount { get; set; }
    }

}
