// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace MarketOrders.ordersJsonTypes
{

    internal class Buyorder
    {

        [JsonProperty( "buyprice" )]
        public string Buyprice
        {
            get;
            set;
        }

        [JsonProperty( "quantity" )]
        public string Quantity
        {
            get;
            set;
        }

        [JsonProperty( "total" )]
        public string Total
        {
            get;
            set;
        }
    }

}
