// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cryptsy.MyOrdersJsonTypes;

namespace Cryptsy
{

    internal class MyOrders
    {

        [JsonProperty("success")]
        public string Success { get; set; }

        [JsonProperty("return")]
        public Return[] Return { get; set; }
    }

}
