// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cryptsy.SampleResponse1JsonTypes;
using Example.MyTradesJsonTypes;

namespace Example
{

    internal class MyTrades
    {

        [JsonProperty("success")]
        public string Success { get; set; }

        [JsonProperty("return")]
        public Trade[] Return { get; set; }
    }

}
