// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace Cryptsy.OrderInfo
{

    internal class OrderResponse
    {

        [JsonProperty( "success" )]
        public string Success
        {
            get;
            set;
        }

        [JsonProperty( "orderid" )]
        public string Orderid
        {
            get;
            set;
        }

        [JsonProperty( "moreinfo" )]
        public string Moreinfo
        {
            get;
            set;
        }
    }

}
