// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using MarketOrders.ordersJsonTypes;
using Newtonsoft.Json;

namespace MarketOrders
{

    internal class Orders
    {

        [JsonProperty( "success" )]
        public string Success
        {
            get;
            set;
        }

        [JsonProperty( "return" )]
        public Return Return
        {
            get;
            set;
        }
    }

}
