// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cryptsy.SampleResponse1JsonTypes;

namespace Cryptsy
{

    internal class SampleResponse1
    {

        [JsonProperty("success")]
        public int Success { get; set; }

        [JsonProperty("return")]
        public Return Return { get; set; }
    }

}
