// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MarketOrders.ordersJsonTypes;

namespace MarketOrders.ordersJsonTypes
{

    internal class Sellorder
    {

        [JsonProperty("sellprice")]
        public string Sellprice { get; set; }

        [JsonProperty("quantity")]
        public string Quantity { get; set; }

        [JsonProperty("total")]
        public string Total { get; set; }
    }

}
