// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace Example.MyTradesJsonTypes
{

    internal class Trade
    {

        [JsonProperty( "tradeid" )]
        public string Tradeid
        {
            get;
            set;
        }

        [JsonProperty( "tradetype" )]
        public string Tradetype
        {
            get;
            set;
        }

        [JsonProperty( "datetime" )]
        public string Datetime
        {
            get;
            set;
        }

        [JsonProperty( "tradeprice" )]
        public string Tradeprice
        {
            get;
            set;
        }

        [JsonProperty( "quantity" )]
        public string Quantity
        {
            get;
            set;
        }

        [JsonProperty( "fee" )]
        public string Fee
        {
            get;
            set;
        }

        [JsonProperty( "total" )]
        public string Total
        {
            get;
            set;
        }

        [JsonProperty( "initiate_ordertype" )]
        public string InitiateOrdertype
        {
            get;
            set;
        }

        [JsonProperty( "order_id" )]
        public string OrderId
        {
            get;
            set;
        }
    }

}
