// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Cryptsy.MyOrdersJsonTypes;

namespace Cryptsy.MyOrdersJsonTypes
{

    internal class Return
    {

        [JsonProperty("orderid")]
        public string Orderid { get; set; }

        [JsonProperty("created")]
        public string Created { get; set; }

        [JsonProperty("ordertype")]
        public string Ordertype { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("quantity")]
        public string Quantity { get; set; }

        [JsonProperty("orig_quantity")]
        public string OrigQuantity { get; set; }

        [JsonProperty("total")]
        public string Total { get; set; }
    }

}
